/*
package massim.tedumas;
import eis.iilang.Percept;
import eis.iilang.Action;
import eis.iilang.Identifier;
import org.apache.logging.log4j.Logger
import eis.iilang.Numeral;

global massim.eismassim.EnvironmentInterface eis;
global Logger logger;

rule "start A13"
when
    $tPercept: TEDUPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[]"))
then
    eis.performAction("A13", new Action("move", new Identifier("e")));
end

rule "previousA13"
when
    $tPercept: TEDUPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[move]"))
    $lastActionResult: TEDUPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[success]"))
then
    eis.performAction("A13", new Action("move", new Identifier("e")));
end

rule "Clear Action: If there is an obstacle in the front after a move A13"
when
    $tPercept: TEDUPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[move]"))
    $lastActionResult: TEDUPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[failed_path]"))
    $lastActionParams: TEDUPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionParams"),
    $direction : percept.getParameters().toString())
then
    eis.performAction("A13", new Action("clear",new Numeral(1), new Numeral(0) ));
end

rule "Clear Action: If the obstacle is successfully cleared A13"
when
    $tPercept: TEDUPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[clear]"))
    $lastActionResult: TEDUPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[success]"))
    $lastActionParams: TEDUPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionParams"),
    $direction: percept.getParameters().toString())
then
    eis.performAction("A13", new Action("move", new Identifier("e")));
end

rule "If massim produces failed_random randomly A13"
when
    $lastActionResult: TEDUPercept(percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[failed_random]"))
then
    eis.performAction("A13", new Action("move", new Identifier("e")));
end

rule "If massim produces failed_status after a move A13"
when
    $tPercept: TEDUPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[move]"))
    $lastActionResult: TEDUPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[failed_status]"))
then
    eis.performAction("A13", new Action("move", new Identifier("e")));
end
*/