package massim.javaagents;
import eis.iilang.Percept;
import eis.iilang.Action;
import eis.iilang.Identifier
import java.util.List;

rule "If there is an obstacle in north"
when
    $par : Percept(getName().equals("lastActionResult"), getParameters().toString().equals("[failed_path]"));
then
    System.out.println("fire detected, starting alarm! ");
    new Action("move", new Identifier("e"));
end