package massim.tedumas;
import eis.iilang.Percept;
import eis.iilang.Action;
import eis.iilang.Identifier;
import java.util.List;
import eis.exceptions.ActException;
import org.apache.logging.log4j.Logger;
import massim.tedumas.TPercept;
import massim.tedumas.agents.BasicAgent
import eis.iilang.Numeral;

global Logger logger;
global massim.eismassim.EnvironmentInterface eis;
global BasicAgent agent;

rule "If simulation starts for the first time"
when
    $tPercept : TPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If simulation starts for the first time : move randomly : " + direction);
end

rule "When previous move is successful"
when
    $tPercept : TPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[move]"))
    $lastActionResult : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[success]"))
    $lastActionParams : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionParams"), $direction : percept.getParameters().toString())
then
    eis.performAction("A1", new Action("move", new Identifier($direction.substring(2,3))));
    logger.info("$$$$$ RULE EXECUTION : " + "When previous move is successful : move randomly : " + $direction.substring(2,3));
end

rule "If there is an obstacle in front of the agentA1 after a move"
when
    $tPercept : TPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[move]"))
    $lastActionResult : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[failed_path]"))
    $lastActionParams : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionParams"), $direction : percept.getParameters().toString())
then
    if($direction.equals("[[n]]"))
        eis.performAction("A1", new Action("clear",new Numeral(0), new Numeral(-1) ));
    else if ($direction.equals("[[s]]"))
        eis.performAction("A1", new Action("clear",new Numeral(0), new Numeral(1) ));
    else if ($direction.equals("[[e]]"))
        eis.performAction("A1", new Action("clear",new Numeral(1), new Numeral(0) ));
     else
        eis.performAction("A1", new Action("clear",new Numeral(-1), new Numeral(0) ));
    logger.info("$$$$$ RULE EXECUTION : " + "If there is an obstacle in front of the agent : clear " + $direction);
end

rule "If the obstacle in front of the agentA1 is successfully cleared"
when
    $tPercept : TPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[clear]"))
    $lastActionResult : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[success]"))
    $lastActionParams : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionParams"), $direction : percept.getParameters().toString())
then
    if($direction.equals("[[0,-1]]"))
        eis.performAction("A1", new Action("move", new Identifier("n")));
    else if ($direction.equals("[[0,1]]"))
        eis.performAction("A1", new Action("move", new Identifier("s")));
    else if ($direction.equals("[[1,0]]"))
        eis.performAction("A1", new Action("move", new Identifier("e")));
     else
        eis.performAction("A1", new Action("move", new Identifier("w")));
    logger.info("$$$$$ RULE EXECUTION : " + "If there is an obstacle in front of the agent : clear " + $direction);
end

rule "If massim produces failed_random randomly"
when
    $lastActionResult : TPercept(percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[failed_random]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If massim produces failed_random randomly : move randomly : " + direction);
end

rule "If massim produces failed_status after a move"
when
    $tPercept : TPercept(percept.getName().equals("lastAction"), percept.getParameters().toString().equals("[move]"))
    $lastActionResult : TPercept(stepID == $tPercept.stepID, percept.getName().equals("lastActionResult"), percept.getParameters().toString().equals("[failed_status]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "failed_status : move randomly : " + direction);
end
