package massim.tedumas;
import eis.iilang.Percept;
import eis.iilang.Action;
import eis.iilang.Identifier;
import java.util.List;
import eis.exceptions.ActException;
import org.apache.logging.log4j.Logger;
import massim.tedumas.TPercept;
import massim.tedumas.agents.BasicAgent;

global Logger logger;
global massim.eismassim.EnvironmentInterface eis;
global BasicAgent agent;

rule "If simulation starts for the first time"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().toString().equals("[]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If simulation starts for the first time : move randomly : " + direction);
end

rule "When previous move is successful"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[success]"))
    $lstactn : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionParams"), $direction : prcpt.getParameters().toString())
then
    eis.performAction("A1", new Action("move", new Identifier($direction.substring(2,3))));
    logger.info("$$$$$ RULE EXECUTION : " + "When previous move is successful : move randomly : " + $direction.substring(2,3));
end

rule "If there is an obstacle in front of the agentA1"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[failed_path]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If there is an obstacle in front of the agent : move randomly : " + direction);
end

rule "If massim produces failed_random randomly"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[failed_random]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If massim produces failed_random randomly : move randomly : " + direction);
end

rule "If massim produces failed_status"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[failed_status]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "failed_status : move randomly : " + direction);
end